Repository bbrockbernd/method_statistics, pull requests merged in 2020-04, with the labels that each got.

#14 Methods annotations
  src/main/java/MethodSummary.java
  src/main/java/StatisticsAction.java
Labels: enhancement

#15 Methods LOC & CC (first version)
  src/main/java/ClassVisitor.java
  src/main/java/MethodSummary.java
  src/main/java/MethodVisitor.java
  src/main/java/StatisticsAction.java
Labels: enhancement

#22 Fixed the lines of code computation.
  src/main/java/ClassVisitor.java
  src/main/java/MethodSummary.java
  src/main/java/MethodVisitor.java
Labels: enhancement

#25 Feature/gui
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/ClassVisitor.java
  src/main/java/StatisticsAction.java
  src/main/java/core/ClassVisitor.java
  src/main/java/core/MethodSummary.java
  src/main/java/core/MethodVisitor.java
  src/main/java/core/StatisticsAction.java
  src/main/java/gui/ColumnInfoFactory.java
  src/main/java/gui/StatisticsToolWindow.java
  src/main/resources/META-INF/plugin.xml
Labels: GUI

#24 Methods signature and javadoc description
  src/main/java/core/MethodSummary.java
  src/main/java/gui/ColumnInfoFactory.java
Labels: Core

#28 Meta/cicd
  .github/workflows/gradle.yml
  Lib/xchart-3.6.2.jar
  Lib/xchart-demo-3.6.2.jar
  README.md
  build.gradle
  config/checkstyle/checkstyle.xml
  src/main/java/core/ClassVisitor.java
  src/main/java/core/MethodSummary.java
  src/main/java/core/MethodVisitor.java
  src/main/java/core/StatisticsAction.java
  src/main/java/gui/ColumnInfoFactory.java
  src/main/java/gui/StatisticsToolWindow.java
  src/test/java/gui/ColumnInfoFactoryTest.java
Labels: enhancement

#30 Fix method overloading problem by displaying params too in chart
  src/main/java/core/ClassSummary.java
  src/main/java/core/MethodSummary.java
  src/main/java/gui/ChartFactory.java
Labels: GUI

#36 Feature/summarize
  src/main/java/core/ClassSummary.java
  src/main/java/core/MethodSummary.java
  src/main/java/core/StatisticsAction.java
  src/main/java/gui/ChartFactory.java
  src/main/java/gui/StatisticsToolWindow.java
Labels: GUI

#34 Markdown action first version
  build.gradle
  src/main/java/core/ClassSummary.java
  src/main/java/core/ClassVisitor.java
  src/main/java/core/MarkdownAction.java
  src/main/java/core/MarkdownVisitor.java
  src/main/java/core/MethodSummary.java
  src/main/java/core/StatisticsAction.java
  src/main/java/gui/ChartFactory.java
  src/main/java/gui/ColumnInfoFactory.java
  src/main/resources/META-INF/plugin.xml
  src/test/java/gui/ColumnInfoFactoryTest.java
Labels: enhancement

#39 Method summary testing
  build.gradle
  src/main/java/core/MethodSummary.java
  src/main/java/gui/ChartFactory.java
  src/main/java/gui/StatisticsToolWindow.java
  src/test/java/core/MethodSummaryTest.java
Labels: Testing

#45 Bugfix/empty methods
  src/main/java/core/MethodSummary.java
Labels: bug

#46 Test markdownvisitor
  src/main/java/core/MarkdownAction.java
  src/main/java/core/MarkdownVisitor.java
  src/main/java/core/markdownStats/LinkSummary.java
  src/main/java/core/markdownStats/MarkdownAction.java
  src/main/java/core/markdownStats/MarkdownGlobalSummary.java
  src/main/java/core/markdownStats/MarkdownSummary.java
  src/main/java/core/markdownStats/MarkdownVisitor.java
  src/main/java/core/methodStats/ClassSummary.java
  src/main/java/core/methodStats/ClassVisitor.java
  src/main/java/core/methodStats/MethodAction.java
  src/main/java/core/methodStats/MethodSummary.java
  src/main/java/core/methodStats/MethodVisitor.java
  src/main/java/gui/markdownDisplay/LinksColumnInfoFactory.java
  src/main/java/gui/markdownDisplay/MarkdownColumnInfoFactory.java
  src/main/java/gui/markdownDisplay/MarkdownToolWindow.java
  src/main/java/gui/methodDisplay/ChartFactory.java
  src/main/java/gui/methodDisplay/MethodColumnInfoFactory.java
  src/main/java/gui/methodDisplay/MethodToolWindow.java
  src/main/resources/META-INF/plugin.xml
  src/test/java/core/LinkSummaryTest.java
  src/test/java/core/MethodSummaryTest.java
  src/test/java/core/markdownStats/MarkdownVisitorTest.java
  src/test/java/gui/methodDisplay/MethodColumnInfoFactoryTest.java
Labels: Testing

#47 Markdown testing - markdown summary tests
  src/main/java/core/markdownStats/LinkSummary.java
  src/main/java/core/markdownStats/MarkdownGlobalSummary.java
  src/main/java/core/markdownStats/MarkdownSummary.java
  src/main/java/core/methodStats/ClassSummary.java
  src/main/java/core/methodStats/MethodSummary.java
  src/main/java/gui/markdownDisplay/LinksColumnInfoFactory.java
  src/main/java/gui/markdownDisplay/MarkdownColumnInfoFactory.java
  src/main/java/gui/markdownDisplay/MarkdownToolWindow.java
  src/test/java/core/markdownStats/LinkSummaryTest.java
  src/test/java/core/markdownStats/MarkdownSummaryTest.java
  src/test/java/core/markdownStats/MarkdownVisitorTest.java
  src/test/java/core/methodStats/MethodSummaryTest.java
  src/test/java/gui/markdownDisplay/LinksColumnInfoFactoryTest.java
  src/test/java/gui/markdownDisplay/MarkdownColumnInfoFactoryTest.java
  src/test/java/gui/methodDisplay/MethodColumnInfoFactoryTest.java
Labels: Testing

#50 Added icons for the toolwindow
  src/main/java/gui/markdownDisplay/MarkdownToolWindow.java
  src/main/java/gui/methodDisplay/MethodToolWindow.java
Labels: GUI

#51 Added test for MethodVisitor class
  src/test/java/core/methodStats/MethodVisitorTest.java
Labels: Testing

#52 Update README.md
  README.md
  images/actions.png
  images/md_files.png
  images/md_links.png
  images/method_signatures.png
  images/methods.png
Labels: documentation
